// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-hZ4e1dyLhMwdPmLyL1awfGuK1bLk-Cw',
    appId: '1:1074050324641:web:9331312be5fbd75acab8e0',
    messagingSenderId: '1074050324641',
    projectId: 'first-app-eba51',
    authDomain: 'first-app-eba51.firebaseapp.com',
    storageBucket: 'first-app-eba51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9iku9au-3TjwIJRv9WHv_2ofGPVI9PLc',
    appId: '1:1074050324641:android:7964dd516c537054cab8e0',
    messagingSenderId: '1074050324641',
    projectId: 'first-app-eba51',
    storageBucket: 'first-app-eba51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6d8dbC5PARaIpOSeJEd-rI5Zp8IZRC1s',
    appId: '1:1074050324641:ios:7c0f3c03f2a6f811cab8e0',
    messagingSenderId: '1074050324641',
    projectId: 'first-app-eba51',
    storageBucket: 'first-app-eba51.appspot.com',
    iosClientId: '1074050324641-i210h2idj4cpvencg8oc3ibh5hth7l0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6d8dbC5PARaIpOSeJEd-rI5Zp8IZRC1s',
    appId: '1:1074050324641:ios:a4b852e623d6d328cab8e0',
    messagingSenderId: '1074050324641',
    projectId: 'first-app-eba51',
    storageBucket: 'first-app-eba51.appspot.com',
    iosClientId: '1074050324641-cqvquhh6sf03oc927qlajt9ci9peo5ad.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
